options:
  merge-default-rules: true
  formatter: stylish
files:
  include: ['app/src/*.s+(a|c)ss', 'app/src/**/*.s+(a|c)ss', 'gallery/src/*.s+(a|c)ss']
rules:
  class-name-format:
    - 2
    - allow-leading-underscore: false
      convention: hyphenatedbem
      ignore: []
  empty-line-between-blocks: 0
  indentation: 0
  leading-zero:
    - 1
    - include: true
  no-mergeable-selectors:
    - 2
    - whitelist: ['from', 'to']
  no-url-domains: 0
  no-url-protocols: 0
  property-sort-order:
    - 1
    - order: smacss
  space-between-parens: 0
  url-quotes: 0
