options:
  merge-default-rules: true
  formatter: stylish
files:
  include: 'app/sass/*.s+(a|c)ss'
rules:
  class-name-format:
    - 2
    - allow-leading-underscore: false
      convention: hyphenatedbem
  empty-line-between-blocks: 0
  leading-zero:
    - 1
    - include: true
  no-mergeable-selectors:
    - 2
    - whitelist: ['from', 'to']
  property-sort-order:
    - 1
    - order: smacss
  url-quotes: 0
