export const GAME_DISPLAY_PRE_GAME = 'GAME_DISPLAY_PRE_GAME';
export const GAME_DISPLAY_PLAYBACK = 'GAME_DISPLAY_PLAYBACK';
export const GAME_DISPLAY_IN_PROGRESS = 'GAME_DISPLAY_IN_PROGRESS';
export const GAME_DISPLAY_POST_GAME = 'GAME_DISPLAY_POST_GAME';

export const GAME_STATE_FINISHED = 'FINAL';
export const GAME_STATE_IN_PROGRESS = 'LIVE';
export const GAME_STATE_NOT_STARTED = 'PREVIEW';

export const GAME_UPDATE_START = 'START';
export const GAME_UPDATE_GOAL = 'GOAL';
export const GAME_UPDATE_END = 'END';

export const PERIOD_OVERTIME = 'OT';
export const PERIOD_SHOOTOUT = 'SO';

export const PLAYBACK_NOT_STARTED = 'PLAYBACK_NOT_STARTED';
export const PLAYBACK_IN_PROGRESS = 'PLAYBACK_IN_PROGRESS';
export const PLAYBACK_FINISHED = 'PLAYBACK_FINISHED';
